/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_day38_cplusplus_TestJniCPlusPlus */

#ifndef _Included_com_example_day38_cplusplus_TestJniCPlusPlus
#define _Included_com_example_day38_cplusplus_TestJniCPlusPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_day38_cplusplus_TestJniCPlusPlus
 * Method:    helloC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_day38_cplusplus_TestJniCPlusPlus_helloC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
