/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_day38_branch_TestJniBranchC */

#ifndef _Included_com_example_day38_branch_TestJniBranchC
#define _Included_com_example_day38_branch_TestJniBranchC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_day38_branch_TestJniBranchC
 * Method:    callC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_day38_branch_TestJniBranchC_callC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
