/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_day38_pressure_TestJniPressure */

#ifndef _Included_com_example_day38_pressure_TestJniPressure
#define _Included_com_example_day38_pressure_TestJniPressure
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_day38_pressure_TestJniPressure
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_day38_pressure_TestJniPressure_startMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_example_day38_pressure_TestJniPressure
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_day38_pressure_TestJniPressure_stopMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
